# Generated by Django 4.2.10 on 2024-02-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commanager',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
