# Generated by Django 4.2.10 on 2024-02-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.CharField(max_length=10)),
                ('datetime', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('provided_by', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('points', models.IntegerField()),
                ('fee', models.IntegerField()),
                ('allowance', models.IntegerField()),
                ('tags', models.CharField(max_length=100)),
                ('comManagerId', models.IntegerField()),
            ],
            options={
                'db_table': 'quest',
            },
        ),
    ]
