# Generated by Django 4.2.10 on 2024-02-17 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
        ('quest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='active',
            field=models.CharField(default='false', max_length=10),
        ),
        migrations.CreateModel(
            name='QuestRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Waiting', max_length=10)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.quest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'quest_registration',
            },
        ),
    ]
