# Generated by Django 4.2.10 on 2024-02-17 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
        ('quest', '0002_alter_quest_active_questregistration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questregistration',
            unique_together={('quest', 'user')},
        ),
    ]
