# Generated by Django 4.2.10 on 2024-02-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0003_alter_questregistration_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='allowance',
            field=models.CharField(max_length=1024),
        ),
    ]
