# Generated by Django 4.2.10 on 2024-02-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('persona', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('points', models.IntegerField()),
                ('field_of_specialization', models.CharField(max_length=100)),
                ('completed_quest_tags', models.CharField(max_length=100)),
                ('active_quest', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
