# Generated by Django 4.2.10 on 2024-02-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('persona', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('field_of_specialization', models.CharField(max_length=200)),
                ('completed_quest_tags', models.CharField(blank=True, default='', max_length=100)),
                ('active_quest', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
